<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="AboutUs.aspx.cs" Inherits="WebApplication1.WebForm5" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    Optimus is designed to help global organizations address their information needs. The world of information is changing and so are the methods of managing it. We provide outsourced technology services to mid-sized organizations who&nbsp;have different needs than Fortune 500 companies. Optimus is designed to meet these&nbsp;specific&nbsp;needs.</p>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    The demand for outsourced technology services is increasing as organizations seek to increase their efficiency. This trend has been improved through advancements in technology and telecommunications that now allow outsourcing services to offer seamless services all over the globe.</p>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    Though outsourcing is a maturing market, mid-sized software companies and enterprises often struggle to find a reliable, nimble, and capable outsourcing vendor. Optimus has the right mix of size, flexibility, and experience to provide high quality outsourcing solutions to mid-sized software companies and enterprises.</p>
<p style="box-sizing: border-box; margin: 0.85em 0px; padding: 0px; border: 0px rgb(225, 225, 225); font-style: normal; font-variant: normal; font-weight: normal; font-stretch: inherit; font-size: 14px; line-height: 23.1px; font-family: &quot;Open Sans&quot;, HelveticaNeue, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(102, 102, 102); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    Optimus is headquartered in Vancouver, Canada and has delivery centers in Canada and India. The founders of Optimus have extensive experience running large global outsourcing companies.</p>
</asp:Content>
